In [ ]:
paragraph = """
Neuro-linguistic programming (NLP) is a pseudoscientific approach to communication, personal development, and psychotherapy that first appeared in Richard Bandler and John
Grinder's book The Structure of Magic I (1975). NLP asserts a connection between neurological processes, language, and acquired behavioral patterns, and that these can 
be changed to achieve specific goals in life.[1][2] According to Bandler and Grinder, NLP can treat problems such as phobias, depression, tic disorders, psychosomatic 
illnesses, near-sightedness,[a] allergy, the common cold,[a] and learning disorders,[3][4] often in a single session. They also say that NLP can model the skills of 
exceptional people, allowing anyone to acquire them.[5][b]
NLP has been adopted by some hypnotherapists as well as by companies that run seminars marketed as leadership training to businesses and government agencies.[6][7]
No scientific evidence supports the claims made by NLP advocates, and it has been called a pseudoscience.[8][9][10] Scientific reviews have shown that NLP is based on o
utdated metaphors of the brain's inner workings that are inconsistent with current neurological theory, and that NLP contains numerous factual errors.[7][11] Reviews also 
found that research that favored NLP contained significant methodological flaws, and that three times as many studies of a much higher quality failed to reproduce the claims 
made by Bandler, Grinder, and other NLP practitioners.[9][10].
"""

In [4]:
#!pip install numpy
#!pip install scipy
#pip install nltk
#!pip install scikit-learn

In [5]:
import numpy 
import scipy
import nltk
import re

In [6]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [7]:
ps = PorterStemmer()
print(ps.stem('histories'))

histori


In [8]:
wl= WordNetLemmatizer()
print(wl.lemmatize('histories'))

history


In [9]:
# Tokecize:Convert the text to sentences then to words:
sentences = nltk.sent_tokenize(paragraph)
print(len(sentences))

9


In [10]:
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [wl.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [11]:
corpus

['neuro linguistic programming nlp pseudoscientific approach communication personal development psychotherapy first appeared richard bandler john grinder book structure magic',
 'nlp asserts connection neurological process language acquired behavioral pattern changed achieve specific goal life',
 'according bandler grinder nlp treat problem phobia depression tic disorder psychosomatic illness near sightedness allergy common cold learning disorder often single session',
 'also say nlp model skill exceptional people allowing anyone acquire',
 'b nlp adopted hypnotherapists well company run seminar marketed leadership training business government agency',
 'scientific evidence support claim made nlp advocate called pseudoscience',
 'scientific review shown nlp based utdated metaphor brain inner working inconsistent current neurological theory nlp contains numerous factual error',
 'review also found research favored nlp contained significant methodological flaw three time many study much 

In [12]:
len(corpus)

9

In [13]:
### Bag of  word
from sklearn.feature_extraction.text import CountVectorizer
bw = CountVectorizer(ngram_range=(1,1))
X= bw.fit_transform(corpus)

In [14]:
bw.vocabulary_
# This means "neuro" is column 66, "linguistic" is column 56, "programming" is column 78, etc.

{'neuro': 66,
 'linguistic': 56,
 'programming': 78,
 'nlp': 68,
 'pseudoscientific': 80,
 'approach': 12,
 'communication': 25,
 'personal': 73,
 'development': 32,
 'psychotherapy': 82,
 'first': 40,
 'appeared': 11,
 'richard': 87,
 'bandler': 14,
 'john': 51,
 'grinder': 45,
 'book': 17,
 'structure': 99,
 'magic': 58,
 'asserts': 13,
 'connection': 27,
 'neurological': 67,
 'process': 77,
 'language': 52,
 'acquired': 3,
 'behavioral': 16,
 'pattern': 71,
 'changed': 21,
 'achieve': 1,
 'specific': 98,
 'goal': 43,
 'life': 55,
 'according': 0,
 'treat': 107,
 'problem': 76,
 'phobia': 74,
 'depression': 31,
 'tic': 104,
 'disorder': 33,
 'psychosomatic': 81,
 'illness': 48,
 'near': 65,
 'sightedness': 94,
 'allergy': 7,
 'common': 24,
 'cold': 23,
 'learning': 54,
 'often': 70,
 'single': 96,
 'session': 92,
 'also': 9,
 'say': 89,
 'model': 63,
 'skill': 97,
 'exceptional': 36,
 'people': 72,
 'allowing': 8,
 'anyone': 10,
 'acquire': 2,
 'adopted': 4,
 'hypnotherapists': 47,
 

In [15]:
corpus[0]

'neuro linguistic programming nlp pseudoscientific approach communication personal development psychotherapy first appeared richard bandler john grinder book structure magic'

In [16]:
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]], dtype=int64)

In [17]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(ngram_range = (1,1))
XX= tf.fit_transform(corpus)

In [18]:
XX[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.24071566, 0.24071566, 0.        , 0.17677416,
        0.        , 0.        , 0.24071566, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.24071566, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.24071566, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.24071566, 0.        , 0.        , 0.        , 0.        ,
        0.17677416, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.24071566, 0.        , 0.        , 0.        ,
        0.        , 0.24071566, 0.        , 0.24071566, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.24071566, 0.        , 0.10196739, 0.        ,
        0.        , 0.        , 0.        , 0.24

In [19]:
# Word2Vec

In [20]:
#!pip install gensim
import gensim

In [21]:
from gensim.models import Word2Vec, KeyedVectors
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

In [22]:
for word in ['NLP', 'psychotherapy', 'communication', 'science', 'language']:
    print(f"{word} in vocab? {'Yes' if word in wv else 'No'}")


NLP in vocab? Yes
psychotherapy in vocab? Yes
communication in vocab? Yes
science in vocab? Yes
language in vocab? Yes


In [23]:
wv['histories']

array([ 5.71289062e-02,  2.27539062e-01,  9.47265625e-02,  1.25976562e-01,
        4.71191406e-02, -9.27734375e-02,  5.41992188e-02,  2.43164062e-01,
        1.07910156e-01, -2.75390625e-01,  1.65039062e-01, -2.14843750e-01,
        3.49121094e-02,  2.98828125e-01, -1.53198242e-02,  2.19726562e-01,
        1.04492188e-01,  4.23828125e-01,  2.99072266e-02, -3.69140625e-01,
       -1.36718750e-01, -2.75390625e-01, -3.63281250e-01, -4.00390625e-02,
       -1.29882812e-01,  2.89306641e-02, -2.67578125e-01,  2.85156250e-01,
       -2.91015625e-01, -2.03125000e-01, -1.05468750e-01, -1.96533203e-02,
       -9.08203125e-02, -2.09960938e-02,  2.29492188e-02,  4.53125000e-01,
        1.31835938e-01, -1.28906250e-01, -2.16484070e-04,  1.27929688e-01,
        8.83789062e-02,  1.61132812e-01, -1.04003906e-01,  1.41601562e-01,
        3.76953125e-01, -3.88183594e-02, -2.96630859e-02,  8.20312500e-02,
        3.14941406e-02, -3.86718750e-01, -8.69140625e-02, -9.42382812e-02,
       -2.38281250e-01, -

In [24]:
wv.most_similar('king')

[('kings', 0.7138046622276306),
 ('queen', 0.6510956287384033),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797566771507263),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422104597091675)]

In [25]:
wv.similarity("man","king")

0.22942671

In [30]:
# Create our own Word2Vec
sentences_for_word2vec = [sentence.split() for sentence in corpus if sentence]  # remove empty strings

In [31]:
# Train Word2Vec model
model = Word2Vec(
    sentences=sentences_for_word2vec,
    vector_size=100,
    window=5,
    min_count=1,
    sg=1
)

In [35]:
# Step 4: Explore
print(model.wv.most_similar('nlp'))

[('contained', 0.29159700870513916), ('run', 0.23731066286563873), ('life', 0.22668011486530304), ('neurological', 0.21837154030799866), ('contains', 0.20869553089141846), ('session', 0.1981584131717682), ('acquired', 0.17630547285079956), ('appeared', 0.17210491001605988), ('goal', 0.15857431292533875), ('exceptional', 0.14514818787574768)]
